name: Docker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: lovesainju

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 3. Build Docker image
      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t notes-app:latest .

      # 4. Run tests (optional)
      - name: Test Docker image
        run: |
          echo "Running tests..."
          # Example: run container and test health
          docker run --rm notes-app:latest python manage.py test

      # # 5. Log in and push to Docker Hub

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # - name: Push Docker image
      #   run: |
      #     docker tag notes-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest

      # # 6. Deploy container
      # - name: Deploy Docker container
      #   run: |
      #     echo "Deploying container..."
      #     docker stop notes-app || true
      #     docker rm notes-app || true
      #     docker run -d --name notes-app -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/notes-app:latest
