name: Deploy to Production

on:
  push:
    branches: [main] # Trigger on push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # GitHub's cloud server

    steps:
      # STEP A: Get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # STEP B: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # STEP C: Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            lovesainju/notes-app:latest
            lovesainju/notes-app:${{ github.sha }}

      # STEP D: SSH into server and deploy
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/noteappdjango
            docker-compose pull
            docker-compose up -d
            docker image prune -f
